import os

Import('env')
Import('config')

def boost_lib(*name):
    if "thread" in name and "date_time" not in name:
        name.append("date_time")
    return ["boost_" + n + config.get('boost_lib_suffix', '') for n in name]

env.Program('mp4dump', [ 'mp4dump.cc', 'mp4.cc' ], 
            LIBS = boost_lib('program_options'))

prefix = os.path.join(config.get('prefix', '.'), 'bin')
env.Install(prefix, ['mp4dump'])
env.Alias('install', prefix)
