"""
Usage:

    scons
    scons build=release,profile
    scons build=all

    etc.
"""

import os, pickle
from utils import suffix_check, compiler_check, boost_ver_check


def save_config(config):
    fd = open(".config", "w")
    pickle.dump(config, fd)
    fd.close()

try:
    assert "configure" not in COMMAND_LINE_TARGETS
    fd = open(".config")
    config = pickle.load(fd)
    fd.close()

except:

	env = {}

	env['CPPPATH'] = filter(None, ARGUMENTS.get("includes", "").split(","))
	env['CPPPATH'].append("libutility")
	env['LIBPATH'] = filter(None, ARGUMENTS.get("libpath", "").split(","))
	env["CPPDEFINES"] = {'BOOST_SP_USE_QUICK_ALLOCATOR': 1,}
	env["CXXFLAGS"] = ['-Woverloaded-virtual', '-Wall', '-std=c++0x']

	boost_lib_suffix = ARGUMENTS.get("boost-suffix", "")
	if not boost_lib_suffix:
		boost_lib_suffix = suffix_check(env)
    
	prefix = ARGUMENTS.get("prefix", ".")

	if os.getenv("CXX"):
		env['CXX'] = os.getenv("CXX")
	else:
		ret = compiler_check()
		if ret:
			env['CXX'] = ret
		else:
			print "Can't find compiler. Exiting"
			Exit(1) 

	tmp_env = Environment()
	tmp_env["CXX"] = env["CXX"]
	chk_conf = Configure(tmp_env, custom_tests = {"boost_ver_check" : boost_ver_check})
	if not chk_conf.boost_ver_check():
		Exit(1)
	tmp_env = chk_conf.Finish()
	
	config = {'env': dict(filter(lambda _: _[1], env.items())), 
              'prefix': prefix, 
              'boost_lib_suffix': boost_lib_suffix}
	              
	save_config(config)

if "printconf" in COMMAND_LINE_TARGETS or "configure" in COMMAND_LINE_TARGETS:
    import pprint
    pprint.pprint(config)
    Exit(0)

targets = {
    "release":   Environment(
		LIBPATH=['/usr/local/lib'], 
        CXXFLAGS = ["-O6"], 
        CPPDEFINES = {'DEBUG': 1, 'WITH_STOPPER': 1, 'NO_THRIFT':1}, 
        ),
    "debug":   Environment(
		LIBPATH=['/usr/local/lib'], 
        CXXFLAGS = ["-O0", "-g", "-fkeep-inline-functions", "-fmerge-all-constants"], 
        CPPDEFINES = {'DEBUG': 1, 'WITH_STOPPER': 1, 'NO_THRIFT':1}, 
        ),
}

try:
    variants = ARGUMENTS["build"]
except KeyError:
    try:
        variants = config["build"]
    except KeyError:
        variants = "release"

if not config.get("build", "") == variants:
    config["build"] = variants
    save_config(config)

if "prefix" in ARGUMENTS:
    config["prefix"] = ARGUMENTS["prefix"]
else:
	config["prefix"] = "/usr/local/bin"
	
save_config(config)

if variants == 'all':
    variants = targets.keys()
else:
    variants = [x for x in variants.split(',') if x in targets]

target_prog = ARGUMENTS.get("program", "all")

for key in variants:
    dir = "." + key
    env = targets[key]
    
    for key, value in config['env'].items():
        if type(value) == type([]):
            env.Append(**{key: value})
        else:
            env[key] = value
            
    Export('env')
    Export('config')
    SConscript('SConscript', build_dir = dir)
